// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeJgb7DPIm8vo81-JzRakl4G4OKCvlU_I',
    appId: '1:232038436692:web:d8608374c6e4bb0c2d42c1',
    messagingSenderId: '232038436692',
    projectId: 'chat-a7a37',
    authDomain: 'chat-a7a37.firebaseapp.com',
    storageBucket: 'chat-a7a37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaPfrOStNpEZQBMd1nGA7u-fPCQfw2imA',
    appId: '1:232038436692:android:cad548b477ec01852d42c1',
    messagingSenderId: '232038436692',
    projectId: 'chat-a7a37',
    storageBucket: 'chat-a7a37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf1NMBigni2-Yzq-GyhbgQnN0Dme2VWkY',
    appId: '1:232038436692:ios:b85d73454086d5352d42c1',
    messagingSenderId: '232038436692',
    projectId: 'chat-a7a37',
    storageBucket: 'chat-a7a37.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf1NMBigni2-Yzq-GyhbgQnN0Dme2VWkY',
    appId: '1:232038436692:ios:b85d73454086d5352d42c1',
    messagingSenderId: '232038436692',
    projectId: 'chat-a7a37',
    storageBucket: 'chat-a7a37.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeJgb7DPIm8vo81-JzRakl4G4OKCvlU_I',
    appId: '1:232038436692:web:7bfa05d608a29ff12d42c1',
    messagingSenderId: '232038436692',
    projectId: 'chat-a7a37',
    authDomain: 'chat-a7a37.firebaseapp.com',
    storageBucket: 'chat-a7a37.appspot.com',
  );
}
